# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2022

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--output ./bin/Debug/'
      
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'iiric visual studio subscription'
    ScriptType: 'InlineScript'
    Inline: |
      Import-Module ./bin/Debug/KQL.dll -Force
      Invoke-Pester -Output Detailed
    azurePowerShellVersion: 'LatestVersion'