# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: win2019

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--output ./bin/Debug/'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Import-Module ./bin/Debug/KQL.dll -Force